import { createLogger, estimateEtsyFees } from "@etsymagazam/core";
import { prisma } from "@etsymagazam/database";

const log = createLogger("finance-agent");

function startOfDayUtc(d = new Date()): Date {
  return new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()));
}

/**
 * Recomputes today's daily_metrics row: gross revenue and estimated Etsy
 * fees from today's paid orders, AI generation cost from today's
 * generation_costs rows, and an estimated net BEFORE any Turkish income
 * tax (see docs — this system records numbers, it does not give tax
 * advice, so `estimatedTaxes` stays informational/zero unless you wire in
 * your own rate).
 */
export async function computeAndStoreDailyFinance(shopId: string): Promise<void> {
  const today = startOfDayUtc();
  const tomorrow = new Date(today.getTime() + 24 * 60 * 60 * 1000);

  const orders = await prisma.etsyOrder.findMany({
    where: { shopId, paidAt: { gte: today, lt: tomorrow } },
  });

  const grossRevenue = orders.reduce((sum, o) => sum + Number(o.grandTotal), 0);
  const estimatedEtsyFees = orders.reduce((sum, o) => {
    const fees = estimateEtsyFees({ priceAmount: Number(o.grandTotal), sellerCountry: "TR" });
    return sum + fees.totalEstimatedFees;
  }, 0);

  const generationCosts = await prisma.generationCost.aggregate({
    where: { createdAt: { gte: today, lt: tomorrow } },
    _sum: { costUsd: true },
  });
  const aiCosts = Number(generationCosts._sum.costUsd ?? 0);

  const estimatedTaxes = 0; // informational only — no tax advice generated by this system
  const estimatedNet = grossRevenue - estimatedEtsyFees - aiCosts - estimatedTaxes;

  await prisma.dailyMetric.upsert({
    where: { shopId_date: { shopId, date: today } },
    update: { grossRevenue, estimatedEtsyFees, aiCosts, estimatedTaxes, estimatedNet, orders: orders.length },
    create: {
      shopId,
      date: today,
      grossRevenue,
      estimatedEtsyFees,
      aiCosts,
      estimatedTaxes,
      estimatedNet,
      orders: orders.length,
    },
  });

  log.info({ shopId, grossRevenue, estimatedEtsyFees, aiCosts, estimatedNet }, "Daily finance recomputed");
}

/** Increments today's autopilot activity counters (generated/published/rejected/optimized/deactivated) — called by the relevant agents as they act. */
export async function bumpDailyAutopilotCounter(
  shopId: string,
  field: "productsGenerated" | "productsPublished" | "productsRejected" | "productsOptimized" | "productsDeactivated",
): Promise<void> {
  const today = startOfDayUtc();
  await prisma.dailyMetric.upsert({
    where: { shopId_date: { shopId, date: today } },
    update: { [field]: { increment: 1 } },
    create: { shopId, date: today, [field]: 1 },
  });
}
